{% set version = "5.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
    name: xz
    version: {{ version }}

source:
    fn:  xz-{{ version }}.tar.bz2                                            # [not win]
    url: http://tukaani.org/xz/xz-{{ version }}.tar.gz                       # [not win]
    sha256: 5dcffe6a3726d23d1711a65288de2e215b4960da5092248ce63c99d50093b93a # [not win]
    git_url: https://github.com/mindw/xz.git                                 # [win]
    patches:
        - 0001-VS2015-Don-t-define-snprintf.patch                            # [win]

requirements:
  build:
    - cmake                     # [win]
    - {{posix}}git              # [win]
    - posix                     # [win]
    - {{posix}}autoconf         # [not linux]
    - {{posix}}automake         # [osx]
    - {{posix}}automake-wrapper # [win]
    - {{posix}}libtool          # [not linux]

build:
    number: 1

test:
    commands:
        - xz --help
        - unxz --help
        - lzma --help
        - conda inspect linkages -n _test xz  # [linux]

about:
    home: http://tukaani.org/xz/
    summary: The xz command is a very powerful program for compressing files
    license: LGPL-2.1 and GPL-2.0

extra:
    recipe-maintainers:
        - ocefpaf
